version: "3"
services:
  commonlit2:
    build:
      context: /home/shugo/kaggle/
      dockerfile: /home/shugo/kaggle/kaggle_env/Dockerfile
    shm_size: "2gb"
    tty: true
    volumes:
      - /home/shugo/kaggle/competitions/commonlit2:/home/working
      - /home/shugo/kaggle/kagglib:/home/working/kagglib
    working_dir: /home/working
    networks:
      - default
    ports:
      - 8888:8888
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
