version: "3"
services:
  commonlit2:
    build:
      context: /home/shugo/kaggle/
      dockerfile: /home/shugo/kaggle/kaggle_env/Dockerfile
    shm_size: "2gb"
    volumes:
      - /home/shugo/kaggle/competitions/commonlit2:/home/working
    working_dir: /home/working
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
