version: "3"
services:
  psp:
    build: .
    shm_size: "2gb"
    volumes:
      - /home/shugo/kaggle/competitions/psp:/home/working
    working_dir: /home/working
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
