version: "3"
services:
  lecr:
    build: .
    volumes:
      - /home/shugo/kaggle/competitions/LECR:/home/working
    working_dir: /home/working
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
